(defproject vix "1.0.0-SNAPSHOT"
  :description "Vix is a document repository and management system."
  :dependencies [[org.clojure/clojure "1.4.0"]
                 [org.clojure/data.codec "0.1.0"]
                 [org.clojure/data.json "0.1.2"]
                 [org.clojure/algo.generic "0.1.0"]
                 [slingshot "0.10.3"]
                 [org.mindrot/jbcrypt "0.3m"]
                 [compojure "1.1.0"]
                 [ring/ring-core "1.1.1"]
                 [ring/ring-servlet "1.1.0"]
                 [enlive "1.0.1"]
                 [clj-time "0.4.3"]
                 [clj-http "0.4.3"]
                 [com.ashafa/clutch "0.4.0-SNAPSHOT"]
                 [com.draines/postal "1.8.0"]
                 [org.jsoup/jsoup "1.6.1"]
                 [commons-codec/commons-codec "1.5"]
                 [org.apache.lucene/lucene-core "3.5.0"]
                 [org.apache.lucene/lucene-queries "3.5.0"]]
  :plugins [[lein-ring "0.7.1"]]
  :ring {:handler vix.routes/app})